### ISSUE TITLE
Toolbar window won't open with mouse click

### ISSUE THREAD

**Issue by xicky** [Unthrottled/themed-components#44]
**Describe the bug**
Toolbar window won't open with mouse click.

**To Reproduce**
1. Click any tab in toolbar, like 'Project', 'Services', 'Terminal', 'Database', etc

**Actual Behaviour**
Toolbar window won't open, and a NullPointerException happened (stack trace is as below)

**Expected Behavior**
Toolbar window can be opened.
(They can be opened using keyboard shortcut, but not with mouse click)

**Environment**
PyCharm 2021.2 (Professional Edition)
Build #PY-212.4746.96
Runtime version: 11.0.11+9-b1504.13 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 3005M
Cores: 8
Registry: wolf.the.problem.solver=false, debugger.watches.in.variables=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: AceJump (3.8.3), GrepConsole (11.10.211.6086.0), IdeaVIM (0.69), org.jetbrains.IdeaVim-EasyMotion (1.6), Statistic (4.1.7), com.andrey4623.rainbowcsv (2.0), com.intellij.ideolog (203.0.27.0), String Manipulation (8.15.203.000.3), fr.mary.olivier.aw-watcher (1.0.8), io.unthrottled.themed-components (1.4.2), net.seesharpsoft.intellij.plugins.csv (2.17.1), mobi.hsz.idea.gitignore (4.2.0), org.toml.lang (0.2.152.4026-212), com.chrisrm.idea.MaterialThemeUI (6.8.0.1), com.jetbrains.intellij.datalore (0.1.13-212), com.leinardi.pycharm.pylint (0.12.2), ru.meanmail.plugin.requirements (2021.4.1-212), PlantUML integration (5.5.1)

Themed Components plugin is at version 1.4.2

**Stack trace**

```
java.lang.NullPointerException
	at io.unthrottled.themed.components.ui.TitlePaneUI.getTitle(TitlePaneUI.kt:212)
	at io.unthrottled.themed.components.ui.TitlePaneUI.access$getTitle(TitlePaneUI.kt:45)
	at io.unthrottled.themed.components.ui.TitlePaneUI$attemptTransparentTitle$2.invoke$lambda-0(TitlePaneUI.kt:200)
	at java.desktop/java.awt.Component.processHierarchyEvent(Component.java:6819)
	at java.desktop/java.awt.Component.processEvent(Component.java:6438)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.Component.createHierarchyEvents(Component.java:5666)
	at java.desktop/java.awt.Container.createHierarchyEvents(Container.java:1470)
	at java.desktop/java.awt.Container.addImpl(Container.java:1166)
	at java.desktop/javax.swing.JDialog.addImpl(JDialog.java:918)
	at java.desktop/java.awt.Container.add(Container.java:997)
	at java.desktop/javax.swing.JDialog.setRootPane(JDialog.java:994)
	at java.desktop/javax.swing.JDialog.dialogInit(JDialog.java:649)
	at java.desktop/javax.swing.JDialog.<init>(JDialog.java:594)
	at com.intellij.openapi.wm.impl.ToolWindowDragHelper$MyDialog.<init>(ToolWindowDragHelper.kt:390)
	at com.intellij.openapi.wm.impl.ToolWindowDragHelper.processMousePressed(ToolWindowDragHelper.kt:139)
	at com.intellij.ui.MouseDragHelper.mousePressed(MouseDragHelper.java:135)
	at com.intellij.openapi.wm.impl.IdeGlassPaneImpl.fireMouseEvent(IdeGlassPaneImpl.java:435)
	at com.intellij.openapi.wm.impl.IdeGlassPaneImpl.preprocess(IdeGlassPaneImpl.java:297)
	at com.intellij.openapi.wm.impl.IdeGlassPaneImpl.dispatchMouseEvent(IdeGlassPaneImpl.java:114)
	at com.intellij.openapi.wm.impl.IdeGlassPaneImpl.dispatch(IdeGlassPaneImpl.java:90)
	at com.intellij.ide.IdeEventQueue.dispatchByCustomDispatchers(IdeEventQueue.java:838)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:730)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by Unthrottled** [comment]
Thank you for taking the time to report this issue! I  can fix this, however I think there is a workaround that you can use for the long term. As of `2021.2` they enabled the MacOS title bar to be transparent [see issue if interested](https://youtrack.jetbrains.com/issue/IDEA-236114?_gl=1*1ckktdj*_ga*MTMzMzI1OTMyMi4xNjI1NzQyMjU3*_ga_0WQ2ZF5VGT*MTYyODc2NjEwMi4yLjAuMTYyODc2NjEwMi4w&_ga=2.130064971.574480988.1628764607-1333259322.1625742257) So I think you can turn that part of the plugin off or remove the plugin (I only added it as a hack, glad they fixed the real issue :tada: )
